# Generated by Django 2.1.2 on 2018-10-27 16:11

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name='interviewers')
    Group.objects.create(name='candidates')


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
